# Умножение двух амтриц

In [4]:
a = [[9, 19, 44], 
     [31, 9, 5], 
     [78, 7, 99]] 
 
b = [[5, 26, 6, 1], 
     [9, -20, -4, 2], 
     [-1, 3 , 42, 5]] 

m = len(a)   # a: m × n
n = len(b)   # b: n × k
k = len(b[0])

c = [[None for __ in range(k)] for __ in range(m)]    # c: m × k

for i in range(m):
    for j in range(k):       
        c[i][j] = sum(a[i][kk] * b[kk][j] for kk in range(n))
  
print(c)

[[172, -14, 1826, 267], [231, 641, 360, 74], [354, 2185, 4598, 587]]


# Умножение двух матриц с помощью функции NumPy 

In [2]:
pip install Numpy  

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np 
mat1 = np.array([[9, 19, 44], [31, 9, 5], [78, 7, 99]]) 
mat2 =  np.array([[5, 26, 6, 1], [9, -20, -4, 2], [-1, 3 , 42, 5]]) 
mat3 = mat1.dot(mat2)   
print("The matrix is:") 
print(mat3)

The matrix is:
[[ 172  -14 1826  267]
 [ 231  641  360   74]
 [ 354 2185 4598  587]]
